### ISSUE TITLE
klayout head tlAssert.cc doesn't compile on MacOS homebrew qt6 6.11.0

### ISSUE THREAD

**Issue by Kazzz-S** [KLayout/klayout#2325]
Originally reported by Stefan. Thanks!

----

Hi Matthias,

a rare klayout comipile error, seems to work for the klayout MacOS CI, but fails for me … 

Qt6 6.11.0 has a bug … nothing that klayout did wrong …
https://github.com/google/mozc/issues/1455

Fixing my local qt header makes the build work again.

Stefan

homebrew qt6 6.11.0
```
../../../src/tl/tl/[tlAssert.cc](http://tlassert.cc/)
In file included from ../../../src/tl/tl/[tlAssert.cc:25](http://tlassert.cc:25/):
In file included from ../../../src/tl/tl/tlException.h:30:
In file included from ../../../src/tl/tl/tlInternational.h:32:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/QString:1:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/qstring.h:15:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/qchar.h:8:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/qglobal.h:51:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/qatomic.h:9:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/qbasicatomic.h:9:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/qatomic_cxx11.h:10:
/opt/homebrew/lib/QtCore.framework/Headers/qyieldcpu.h:37:5: error: implicitly declaring library function '__yield' with type 'void ()' [-Werror,-Wimplicit-function-declaration]
   37 |     __yield();              // Generic
      |     ^
/opt/homebrew/lib/QtCore.framework/Headers/qyieldcpu.h:37:5: note: include the header <arm_acle.h> or explicitly provide a declaration for '__yield'
1 error generated.
```

**Comment by Kazzz-S** [comment]
### I could reproduce the error:

<img width="1100" height="622" alt="Image" src="https://github.com/user-attachments/assets/90623547-6371-44b8-8acc-1d511787148d" />

**Comment by Kazzz-S** [comment]
### Fix with Gemini

<img width="1473" height="1151" alt="Image" src="https://github.com/user-attachments/assets/822c4cdd-873a-4e1c-87e3-40a0b28c92b3" />

**patch**
```
--- qyieldcpu.h.org	2026-03-18 07:34:29
+++ qyieldcpu.h	2026-04-10 12:16:21
@@ -20,6 +20,16 @@
 void _mm_pause(void);       // the compiler recognizes as intrinsic
 #endif
 
+/*
+ * For ARM64 Clang/GCC, include <arm_acle.h> to ensure __yield() is declared
+ * when __has_builtin(__yield) is true.
+ */
+#if defined(Q_PROCESSOR_ARM) && (defined(Q_CC_CLANG) || defined(Q_CC_GNU))
+#  if __has_include(<arm_acle.h>)
+#    include <arm_acle.h>
+#  endif
+#endif
+
 QT_BEGIN_NAMESPACE
 
 Q_ALWAYS_INLINE
@@ -33,7 +43,11 @@
     noexcept
 #endif
 {
-#if __has_builtin(__yield)
+#if defined(Q_PROCESSOR_X86) && __has_builtin(__builtin_ia32_pause)
+    __builtin_ia32_pause();
+#elif defined(Q_PROCESSOR_ARM) && __has_builtin(__builtin_arm_yield)
+    __builtin_arm_yield();
+#elif __has_builtin(__yield)
     __yield();              // Generic
 #elif defined(_YIELD_PROCESSOR) && defined(Q_CC_MSVC)
     _YIELD_PROCESSOR();     // Generic; MSVC's <atomic>
@@ -63,4 +77,4 @@
 
 QT_END_NAMESPACE
 
-#endif // QYIELDCPU_H
+#endif // QYIELDCPU_H
\ No newline at end of file
```

----

**Dry Run**
```
patch --dry-run qyieldcpu.h < qyieldcpu.patch
```

----

### test build with `./build4mac.py -q qt6brew -r hb34 -p hb313`

<img width="903" height="640" alt="Image" src="https://github.com/user-attachments/assets/dd6a27e9-50f8-452d-8cd0-be86cd16bc77" />
